export const HEADSHOT_PROMPTS = {
  corporate: `Transform this photo into a polished professional corporate headshot with meticulous attention to detail. Imagine the subject has just stepped into a high-end corporate portrait studio for their executive team photo.

COMPOSITION & FRAMING: Frame the subject from mid-chest up with precise, professional positioning. The subject's FACE must be perfectly centered horizontally in the frame - their nose should align with the vertical center line of the image. Vertically, position the subject's eyes in the upper third of the frame following the classic rule of thirds for portraits - specifically, the eyes should be approximately one-third down from the top edge. This creates balanced, professional composition with appropriate headroom above (roughly the width of one hand or 10-15% of frame height) and ensures the full face, head, and upper shoulders are completely visible within the frame with no cropping. The subject's body is angled approximately 25-30 degrees to the camera's right or left (whichever is most flattering), while their head turns back toward the camera to face forward, creating dimension. The face itself remains centered and prominent. Shoulders are relaxed, level, and symmetrical in the frame. CRITICAL: Ensure the entire head including the top of the hair and both ears (if visible) are completely within the frame boundaries - nothing should be cut off at the edges.

WARDROBE & STYLING: The subject wears impeccably tailored business professional attire. Picture a crisp, pressed dress shirt or blouse in classic white or subtle light blue, paired with a expertly fitted blazer in charcoal gray, navy blue, or classic black. The fabric has a subtle texture - think fine wool or high-quality cotton blend. Collar sits perfectly, shoulders fit precisely, and everything looks freshly pressed. The overall look conveys success, attention to detail, and professional excellence.

BACKGROUND: A pristine, professional studio background in neutral tones. Imagine a seamless paper backdrop in soft dove gray, warm cream, or cool light blue-gray. The background has subtle tonal variation created by graduated lighting - slightly brighter behind the subject's head to create separation, gently darkening toward the edges. The gradient is smooth and professional, never flat or distracting. The background completely melts away into soft focus.

LIGHTING DESIGN: Premium three-point studio lighting executed flawlessly. The main key light is a large octagonal softbox positioned 45 degrees to the subject's right or left and slightly elevated, creating gentle dimensional shadows that sculpt the face beautifully. This light is bright enough to illuminate without washing out, creating soft catchlights that make the eyes sparkle with life and warmth. A secondary fill light at 50% power softens any harsh shadow lines while maintaining dimension. A subtle hair light from above and behind creates a delicate rim of light separating the subject from the background and adding professional polish. The lighting is even, flattering, and pristine - revealing clear, healthy skin tone with natural texture preserved.

TECHNICAL EXECUTION: Captured with professional portraiture equipment - think 85mm f/1.8 or 70-200mm f/2.8 lens at moderate aperture (f/4 to f/5.6) for the perfect balance of sharp facial focus and gently blurred background. Every detail is critically sharp where it matters - individual eyelashes, skin texture showing natural pores and authenticity, hair strands with dimension and life, and fabric weave in the clothing. The depth of field gracefully falls off past the face, creating separation.

EXPRESSION & ENERGY: Match and enhance the subject's natural expression from the original photo. If they're smiling, refine it into a confident, warm, and genuine professional smile with natural eye engagement - the kind that communicates trustworthiness and approachability. If they have a more neutral expression, enhance it into a calm, confident, and composed look with engaged eyes that connect directly with the viewer. The expression should feel authentic to who they are, never forced or artificial. Their eyes should have life, sparkle, and genuine presence.

AUTHENTICITY MANDATE: Preserve every aspect of the subject's unique identity with complete fidelity - their exact facial structure, distinctive features, natural skin tone and texture (including any beauty marks, freckles, or character), hair color and style with all its natural texture and movement, eye color with authentic depth, and their true likeness. This is them at their professional best, not someone else. Maintain natural skin texture - real pores, natural characteristics - while ensuring excellent lighting and image quality. No artificial smoothing or unrealistic enhancement.

COLOR & MOOD: Rich, accurate color reproduction with a slightly warm color temperature (around 5000-5500K) that flatters skin tones beautifully. Colors are vivid but natural - never oversaturated or dull. The overall palette communicates professionalism, trustworthiness, competence, and approachability.

The final image is the kind of headshot that opens doors - perfect for LinkedIn, corporate websites, executive team pages, business cards, conference materials, or any professional context where first impressions matter. This is corporate photography at its finest: polished, professional, and perfectly executed.`,
  
  creative: `Transform this photo into a stunning creative professional portrait with an artistic, modern aesthetic. Picture the subject in a beautiful natural light setting that showcases their personality and creativity while maintaining professional polish.

COMPOSITION & FRAMING: An intimate, engaging close-up portrait capturing the subject from shoulders up, with the face as the clear focal point. CRITICAL POSITIONING: The subject's face must be centered horizontally in the frame - align their nose with the vertical center line of the image to ensure balanced composition. Position the subject's eyes approximately one-third down from the top of the frame, following portrait photography's golden ratio. This creates the perfect balance of headroom (about 8-12% of frame height above the top of their head) while allowing the face to fill the frame generously for that intimate, engaging feel. The entire head including hair and the tops of ears must be completely visible - absolutely no cropping at the top or sides of the head. While the face is centered, the subject's body can be relaxed and naturally angled to add dimension, creating a dynamic yet balanced composition. The framing should feel modern, fresh, and authentic - this is a real moment of connection, not a stiff pose, but still professionally composed with the face properly centered and positioned.

WARDROBE & STYLING: Smart casual with creative flair and personality. Imagine a perfectly fitted blazer or jacket in a rich, distinctive color - perhaps burgundy, forest green, camel, rust, or charcoal - that complements their skin tone beautifully. Underneath, a simple but stylish crew-neck tee, casual button-up in chambray or linen, or elevated basics. The clothing has texture and character - maybe a subtle pattern, interesting weave, or quality fabric that catches light. Everything fits impeccably and feels authentically them - creative, professional, but approachable and real. This is what they'd wear to a creative agency meeting or co-working space.

BACKGROUND & ENVIRONMENT: A gorgeously defocused background that suggests personality and context without distraction. Picture warm, glowing bokeh circles and soft blurred shapes in the background - perhaps natural light filtering through windows or plants, the warm tones of a modern creative workspace with exposed brick or wood, hints of greenery from indoor plants, or the soft glow of ambient lighting. The bokeh has a dreamy, artistic quality with warm honey, amber, cream, and soft green tones. Everything melts into beautiful soft focus, creating depth and atmosphere while keeping all attention on the subject.

LIGHTING DESIGN: Absolutely beautiful natural window light with the quality of golden hour. Imagine soft, warm sunlight streaming through a large window positioned to the side and slightly in front of the subject. The light is directional and sculpting, wrapping around the contours of their face and creating gentle shadows that add dimension and character. It's the kind of light that makes skin glow from within. The shadows are soft and filled with subtle reflected light, maintaining detail while creating that coveted three-dimensional quality. The overall temperature is warm - golden amber tones with hints of honey. The light creates natural catchlights in the eyes that sparkle with life and warmth. There's a gentle rim light from environmental bounce, separating the subject from the background beautifully.

TECHNICAL EXECUTION: Shot with a fast prime lens - 85mm f/1.4, 50mm f/1.8, or 35mm f/1.4 - wide open or nearly wide open for that gorgeous shallow depth of field. The focus is laser-sharp exactly on the subject's eyes, capturing every detail with stunning clarity - individual eyelashes, iris detail, natural skin texture with real pores and character, hair strands with life and movement. Past the plane of focus, everything gracefully dissolves into creamy, smooth bokeh that's absolutely dreamy. The depth of field and bokeh quality are premium and artistic.

EXPRESSION & ENERGY: Preserve and enhance the subject's authentic expression and energy from the original photo. If they're naturally smiling, capture a genuine, warm, relaxed smile that feels real and unforced - maybe eyes slightly crinkled with authentic joy, the kind of expression that draws people in. If they have a more subtle or neutral expression, work with that - a calm, confident, thoughtful look with engaged eyes and subtle warmth. The key is authenticity - this should feel like a genuine moment of connection, not a posed photo. Their personality shines through in their eyes, which should have life, depth, and sparkle. The overall energy is confident yet approachable, creative yet professional, warm and human.

AUTHENTICITY MANDATE: Maintain complete fidelity to the subject's unique identity and authentic appearance. Preserve their exact facial features, bone structure, distinctive characteristics, natural skin tone and texture (including freckles, beauty marks, or natural variation), hair color and texture with all its natural movement and life, eye color with depth and authenticity, and their true likeness. Show real skin with natural texture - visible pores, authentic character, genuine beauty. This is them at their best, not artificially altered or smoothed. Every detail that makes them uniquely themselves must be preserved with care.

COLOR & MOOD: Warm, rich color palette with a golden hour quality. Colors are vibrant and alive but natural and harmonious - warm ambers, honey tones, soft creams, and earthy accents. Skin tones glow with warmth and health. The white balance leans slightly warm (around 5500-6000K) creating that coveted golden hour feel. There's richness and depth to the colors without oversaturation.

The final image feels artistic, authentic, warm, and completely modern. This is the kind of portrait that stands out on creative portfolios, startup websites, speaker profiles, or anywhere creative professionals want to show both their professionalism and personality. The aesthetic is approachable, genuine, contemporary, and beautifully crafted - perfect for designers, freelancers, startup founders, creative directors, or anyone in the creative industries who wants to show their human side while maintaining professional excellence.`,

  techvisionary: `Transform this photo into a cutting-edge tech visionary portrait that screams Silicon Valley innovation and future-forward thinking. This is the headshot of someone who's changing the world through technology - think startup founders, CTOs, tech entrepreneurs, and digital innovators.

COMPOSITION & FRAMING: Modern, confident composition with the subject framed from upper chest up. CRITICAL POSITIONING: Face must be perfectly centered horizontally - nose aligned to the vertical center line of the frame. Eyes positioned one-third from the top following portrait best practices, with balanced headroom of 10-12% above the crown. The entire head including hair must be fully visible with no cropping. The subject's body is angled slightly (20-25 degrees) creating dynamic energy, but the face remains the centered focal point. The composition feels contemporary, energetic, and forward-thinking - this is someone comfortable in the digital age.

WARDROBE & STYLING: Smart casual tech aesthetic - the uniform of innovation. Picture a perfectly fitted dark crew neck t-shirt in black, charcoal, or navy (think Steve Jobs simplicity), or a minimalist zip-up hoodie in premium fabric. Alternatively, a casual button-up shirt with rolled sleeves over a quality tee. The look is intentionally understated but premium - high-quality fabrics, perfect fit, effortless confidence. This is someone who doesn't need a suit to prove they're serious. Clean, modern, minimal, authentic. Tech industry casual done right.

BACKGROUND & ENVIRONMENT: A beautifully blurred modern tech environment with distinctive character. Imagine soft bokeh featuring cool blue and cyan tones mixed with warm amber accents - suggesting LED strips, monitor glow, or modern office lighting. The background hints at a contemporary tech workspace: subtle bokeh shapes suggesting sleek monitors, modern architecture with glass and metal, perhaps soft blue light from screens, or minimalist industrial design elements. Cool grays, deep blues, subtle teals, with strategic warm accent lights. The depth of field creates separation while maintaining that tech-forward atmosphere. Everything is gorgeously out of focus, atmospheric, and modern.

LIGHTING DESIGN: Contemporary mixed lighting with a tech-forward edge. The key light is bright, clean, and modern - imagine window light or LED panel creating even, flattering illumination with a slightly cool color temperature (5500-6000K) that gives that crisp, digital-age clarity. Add subtle colored accent lighting for the signature tech look - perhaps a cool blue rim light on one side (suggesting monitor glow) and/or a warm amber/orange accent from the other direction creating that modern two-tone lighting popular in tech photography. The interplay of cool and warm tones creates dimension and visual interest. The lighting feels intentional, modern, and innovative - not traditional studio lighting but contemporary and fresh. Catchlights in the eyes show engagement and intelligence.

TECHNICAL EXECUTION: Shot with premium glass - 50mm f/1.4 or 85mm f/1.8 at wide aperture for that gorgeous shallow depth of field that's become synonymous with modern tech portraiture. Focus is razor-sharp on the eyes, capturing every detail with digital clarity - crisp eyelashes, iris detail with depth, natural skin texture showing authenticity, hair with dimension. The bokeh is smooth, circular, and premium - balls of light from background sources create visual interest. High resolution, exceptional sharpness, modern aesthetic.

EXPRESSION & ENERGY: Preserve and enhance the subject's authentic expression from the original. If they're smiling, capture confident, approachable warmth - the kind of smile that makes investors believe in your vision and users trust your product. If more neutral or serious, amplify that with thoughtful confidence, focused intelligence, and quiet determination - the expression of someone solving hard problems. Their eyes should communicate intelligence, vision, curiosity, and authentic presence. The energy is confident but not arrogant, focused but approachable, innovative and forward-thinking. This is someone building the future.

AUTHENTICITY MANDATE: Preserve complete fidelity to the subject's unique identity. Maintain their exact facial features, bone structure, natural skin tone and texture (including all authentic characteristics), hair style and color with natural texture, eye color with depth, and true likeness. Show real skin with natural pores and authenticity - tech leaders are real humans, not artificially smoothed avatars. This is them at their innovative best, completely authentic.

COLOR & MOOD: Modern color palette with tech-forward character. The overall temperature balances cool and warm - primarily cool/neutral (5500-6000K) for that digital clarity, with strategic warm accents (amber, orange) creating visual interest. Think cool blues and teals mixed with warm coppers and ambers - the signature look of modern tech photography. Colors are vibrant and contemporary but natural. Skin tones remain accurate and healthy despite the creative lighting. The palette communicates innovation, intelligence, forward-thinking, and digital-age confidence.

The final image belongs on TechCrunch, in pitch decks, on startup websites, at SXSW, or anywhere tech innovators are making waves. This is the modern tech visionary aesthetic - confident, innovative, authentic, and undeniably forward-thinking. Perfect for startup founders, tech entrepreneurs, CTOs, engineers, developers, product managers, or anyone in the tech industry who's building what's next.`,

  celebrity: `Transform this photo into a stunning high-end celebrity portrait with luxury magazine editorial quality. This is the kind of glamorous, polished headshot you'd see in Vanity Fair, Vogue, or on the cover of prestigious entertainment magazines - pure star power and sophisticated elegance.

COMPOSITION & FRAMING: Glamorous close-up portrait from shoulders up with the subject commanding every pixel. CRITICAL POSITIONING: Face must be perfectly centered horizontally with nose aligned to the vertical center line of the frame. Eyes positioned precisely one-third from the top edge creating that magazine-perfect composition. Headroom of 8-10% creates intimate framing - closer than traditional headshots for that celebrity intimacy and connection. The entire head including styled hair must be fully visible. The subject's body is elegantly angled (25-30 degrees) with shoulders creating beautiful lines, while their face remains the centered star of the composition. The posture is confident, elegant, and magnetic - they know they're captivating. Every element communicates star quality.

WARDROBE & STYLING: Elevated, sophisticated, and undeniably glamorous. Picture impeccably tailored designer attire - perhaps a structured blazer in luxe fabric like velvet, silk, or premium wool in rich jewel tones (emerald, sapphire, ruby, or classic black), or an elegant high-neck top in quality materials. Alternatively, timeless sophistication in black turtleneck, designer leather jacket, or contemporary tailored pieces. The styling is polished and intentional - think what celebrities wear to premieres, award shows, or high-end photo shoots. Quality is evident in every detail: perfect fit, luxurious fabrics with sheen and texture, elegant lines. Accessories if visible are subtle but premium - delicate jewelry that catches light. Everything communicates refinement, success, and star power.

BACKGROUND & ENVIRONMENT: Luxurious, elegant backdrop with premium quality. Option 1: Seamless studio background in rich, sophisticated tones - deep charcoal, elegant navy, warm bronze, or timeless black - with beautiful tonal gradation and professional studio lighting creating depth and dimension. Option 2: Gorgeously blurred high-end environment - perhaps soft bokeh suggesting luxury interior with warm lighting, elegant architectural details, or sophisticated setting. The background has depth and richness but never competes with the subject - everything serves to make them the undeniable star. Colors are rich, saturated, and luxurious. The aesthetic screams premium quality and sophistication.

LIGHTING DESIGN: Masterful, glamorous lighting executed with precision and artistry. Classic Hollywood-inspired beauty lighting creating absolutely flawless, luminous results. The key light is a large, soft source positioned nearly frontal and slightly elevated - think beauty dish or large octabox creating the characteristic even, glowing illumination that makes skin look radiant and flawless. This lighting minimizes shadows under eyes and creates a luminous, polished look. Catchlights in the eyes are large and bright, creating sparkle and life. Fill lighting is generous, maintaining a more moderate contrast ratio than editorial work - glamorous but flattering, polished but not flat. Possible rim or hair light adds separation and dimension, creating that professional polish. The lighting enhances natural beauty while creating that unmistakable celebrity glow - skin looks radiant, healthy, and absolutely luminous. This is lighting designed to make someone look their absolute best.

TECHNICAL EXECUTION: Premium optics creating the signature celebrity portrait look. Shot with 85mm f/1.4 or 70-200mm f/2.8 at moderate aperture (f/2.8-f/4) for gorgeous depth of field that keeps the face perfectly sharp while creating beautiful background separation. Every detail is captured with exceptional clarity - individual lashes creating natural glamour, iris detail with depth and sparkle, skin texture that's real but polished, hair with dimensional shine and life, fabric texture showing quality. The depth of field creates beautiful bokeh and separation. High resolution, exceptional sharpness, magazine-quality technical execution. The image quality itself communicates premium, high-end production value.

EXPRESSION & ENERGY: Preserve and elevate the subject's natural expression with celebrity presence. If they're smiling in the original, capture that radiant, confident smile that lights up red carpets - warm, engaging, magnetic, with eyes that sparkle with charisma and charm. If more neutral or subtle, work with that energy - perhaps a knowing, confident expression with subtle smile playing at the corners of the mouth, or composed elegance with intensity in the eyes. The expression should feel authentic to them while communicating star quality, confidence, and magnetic presence. Their eyes should be engaged, sparkling, and full of life - this is someone comfortable with all eyes on them. The energy is confident, charismatic, polished, and undeniably captivating. This is star power.

AUTHENTICITY MANDATE: Preserve the subject's unique identity and authentic beauty with complete fidelity. Maintain their exact facial features, bone structure, distinctive characteristics that make them recognizable, natural skin tone (while beautifully lit), hair color and style with all its styled perfection, eye color with depth and sparkle, and their true likeness. This is professional, polished photography - skin looks radiant and healthy with beautiful lighting, but maintain natural texture and authentic character. This is them at their most glamorous and polished, but still authentically them. Real beauty, professionally captured and beautifully presented.

COLOR & MOOD: Rich, luxurious color palette with sophisticated warmth. Colors are vibrant, saturated, and elegant - think jewel tones, rich neutrals, warm golds, deep blacks. Skin tones are warm, radiant, and healthy with that celebrity glow. Overall color temperature leans slightly warm (5200-5600K) creating flattering, luxurious warmth. There's richness and depth in every color - nothing feels flat or dull. The palette communicates luxury, sophistication, glamour, and star quality. Colors pop with life and vibrancy while remaining elegant and refined.

The final image is pure celebrity glamour - the kind of portrait that belongs in Vanity Fair, on entertainment websites, in press kits, or framed in an agent's office. This is high-end portrait photography at its most polished and glamorous, perfect for actors, musicians, entertainers, influencers, public figures, or anyone who wants that sophisticated celebrity aesthetic. Polished, radiant, captivating, and undeniably star-quality.`,

  artistic: `Transform this photo into a bold, artistic portrait with creative edge and authentic individuality. This is for the rebels, the artists, the creatives who refuse to fit into conventional boxes - think musicians, artists, designers, creatives, and free spirits who want their headshot to reflect their unique vision and authentic voice.

COMPOSITION & FRAMING: Dynamic, intentional composition that breaks some rules while maintaining professional impact. Frame from mid-chest up with the subject positioned powerfully. CRITICAL POSITIONING: While maintaining creative freedom, keep the face centered horizontally with nose aligned to the vertical center line. Eyes positioned approximately one-third from top, but allow for creative interpretation - perhaps slightly tighter framing or more generous headroom (8-14%) depending on the overall artistic vision. The entire head must be visible. The subject's body can be angled dynamically, perhaps with more pronounced turn or unique posture - there's energy and intention in how they hold themselves. Maybe they're leaning slightly forward with intensity, or positioned with confident asymmetry. The composition feels alive, unconventional but purposeful, and uniquely them.

WARDROBE & STYLING: Authentic personal style with creative edge and individuality. This could be many things: vintage band tee with worn-in character, leather or denim jacket with personality, statement piece with unique texture or pattern, all-black minimalist elegance, bold prints, layered looks with visual interest, or whatever genuinely represents their creative identity. Perhaps there's unique jewelry - vintage rings, meaningful necklaces, or personal talismans. Maybe there are tattoos visible adding to their story. The styling is intentionally non-corporate, creatively bold, and authentically them. Fabrics have texture and character - distressed denim, soft cotton, leather with patina, vintage wool. This is someone who dresses for creative expression, not corporate approval. The look feels genuine, lived-in, and full of personality.

BACKGROUND & ENVIRONMENT: Creative, atmospheric background with character and mood. Imagine rich, moody tones with artistic quality - perhaps deep burgundy, forest green, burnt orange, midnight blue, or dramatic black. The background could be textured with character - exposed brick slightly out of focus, weathered walls with history, urban elements, or creative studio environment. Alternatively, beautiful bokeh with artistic lighting creating ambiance - perhaps string lights, practical lamps, or creative lighting setups creating atmospheric glow. The background has personality and contributes to the overall mood without overwhelming. Colors are rich, saturated, and intentional - creating atmosphere and supporting the subject's creative energy. There's depth, texture, and visual interest balanced with beautiful separation.

LIGHTING DESIGN: Creative, intentional lighting with artistic character and mood. Move beyond standard portrait lighting into more expressive territory. Perhaps dramatic side lighting creating bold shadows and dimension, or moody Rembrandt lighting with rich contrast, or even creative colored gels adding artistic flair - maybe subtle warmth on one side and cool tones on the other, or bold colored accent lights creating visual drama. The lighting could be slightly edgier - more contrast, deeper shadows with detail, defined dimension. Think music video aesthetic, album cover lighting, or art gallery portrait. The light sculpts the face with intention, creates mood and atmosphere, and adds to the overall artistic impact. Catchlights still bring life to the eyes. The lighting feels creative, intentional, moody, and artistically bold while remaining flattering and professional.

TECHNICAL EXECUTION: Shot with creative intention - perhaps 50mm f/1.8 or 35mm f/1.4 for a slightly wider, more environmental feel, or 85mm for classic compression. Aperture choices create depth of field that serves the artistic vision - perhaps very shallow for dreamy bokeh, or slightly stopped down to include environmental texture. Focus is still sharp on the eyes capturing detail and life, but there's creative freedom in how the rest of the image is rendered. Perhaps there's intentional film grain added for texture and vintage character, or the image is crisp and digital-sharp for modern edge. Colors might be slightly pushed for creative impact - richer, more saturated, with intentional color grading that serves the mood. The technical execution serves the creative vision while maintaining professional quality.

EXPRESSION & ENERGY: Preserve and amplify the subject's authentic personality and creative spirit from the original photo. If they're smiling, let it be genuine and full of personality - maybe a knowing smile, mischievous grin, or authentic joy. If more serious or intense, embrace that - perhaps contemplative depth, focused intensity, quiet confidence, or even subtle defiance. The key is authentic creative energy and individual personality. Their eyes should communicate depth, intelligence, creativity, and authentic presence - maybe intensity, maybe warmth, maybe both. The expression should feel genuinely them, not performed. The energy is confident, authentic, creative, individual, and unapologetically real. This is someone who knows who they are and doesn't need external validation.

AUTHENTICITY MANDATE: Preserve every aspect of the subject's unique identity with reverence and authenticity. Maintain their exact facial features, bone structure, distinctive characteristics (tattoos, piercings, unique features), natural skin tone and texture with all authentic detail, hair color and style including any creative color or unique cut, eye color with depth, and their unmistakable true likeness. Embrace natural texture, character lines, freckles, beauty marks - these are badges of authenticity. This is them in their creative truth, not sanitized or corporatized. Every detail that makes them uniquely themselves is honored and celebrated.

COLOR & MOOD: Rich, moody, artistic color palette with creative intention. Colors might be deep and saturated - burgundies, deep blues, rich greens, warm ambers, or dramatic blacks. Or perhaps there's creative color treatment - slightly desaturated with pops of color, vintage warmth, cool tones with warm accents, or bold color contrasts. Skin tones remain authentic but the overall palette serves the artistic mood. The aesthetic might lean slightly warmer or cooler based on creative vision. There's intentionality in every color choice, creating mood, atmosphere, and artistic impact.

The final image feels authentic, artistic, creative, and boldly individual. This belongs in creative portfolios, music press kits, gallery artist statements, independent film credits, or anywhere creative professionals want to show their authentic voice and individual vision. Perfect for musicians, visual artists, photographers, filmmakers, writers, creative directors, or anyone in creative fields who wants their headshot to reflect their artistic identity and authentic spirit. This is creative portraiture with edge, depth, and genuine personality.`,
  
  editorial: `Transform this photo into a stunning, dramatic editorial portrait with the sophisticated aesthetic of high-end fashion magazines and fine art photography. This is a powerful, cinematic black and white photograph that commands attention and tells a story.

COMPOSITION & STORYTELLING: A striking portrait captured from mid-chest up, composed with intentional artistry and precise positioning. ESSENTIAL FRAMING RULES: The subject's face must be the centered anchor of the composition - position their face in the horizontal center of the frame with their nose aligned to the vertical center line (even if their body is turned or angled for dramatic effect). The subject's eyes should be positioned in the upper third of the frame following classical portraiture principles - specifically about one-third down from the top edge. Ensure proper headroom above the head (approximately 10-12% of frame height) - enough space to breathe without feeling cramped, but not so much that the subject feels lost. CRITICAL: The entire head including the top of the hair, crown, and full facial structure must be completely visible within the frame - no cropping at the top, sides, or anywhere on the head. The subject can be positioned in a dynamic pose - straight-on with intense direct gaze, or in an elegant three-quarter turn - but their face remains centered as the compositional anchor. Their posture conveys confidence, strength, and thoughtful presence. Perhaps one hand is positioned thoughtfully near their face, chin, or chest creating visual interest, or both arms are relaxed but intentional. Every element feels deliberate and meaningful, like a frame from a cinematic story, but the face is always properly centered and positioned as the hero of the composition.

WARDROBE & STYLING: Sophisticated, refined attire with beautiful texture and depth. Picture a superbly tailored jacket or blazer in rich charcoal, deep black, or elegant dark gray - the kind of garment where you can see the quality of the fabric and the precision of the tailoring. The fabric has visible texture and character - perhaps a subtle herringbone weave, fine wool with dimensional quality, or structured cotton with presence. The styling is elevated and contemporary but not corporate - think editorial fashion, art gallery opening, or creative executive. Clean lines, impeccable fit, understated elegance. The clothing adds to the overall narrative of sophistication and intentionality.

BACKGROUND & ATMOSPHERE: A deep, luxurious black or very dark charcoal background with subtle tonal variation and depth. This isn't a flat black void - it has dimension and life. Imagine graduated tones with the background slightly lighter behind the subject's head and shoulders (creating crucial separation), gradually deepening to rich, velvety black toward the edges. The tonal gradation is smooth and sophisticated, adding three-dimensionality. This timeless background approach echoes the masters of portrait photography - think Yousuf Karsh, Irving Penn, or Annie Leibovitz's iconic work. The darkness creates drama, intimacy, and focus entirely on the subject.

LIGHTING DESIGN - MASTERFUL EXECUTION: Dramatic, sculptural studio lighting executed with precision and artistry. The lighting follows classical techniques - imagine Rembrandt lighting, split lighting, or dramatic side lighting. A single powerful key light is positioned 60-90 degrees to the side of the subject, creating bold, intentional shadows that sculpt the face with dimension and drama. This creates a stunning interplay of light and shadow - bright, luminous highlights on one side of the face transitioning beautifully into rich, detailed shadows on the other side. The contrast is striking and bold but never harsh - shadows maintain detail and nuance, never going completely black. Look for the characteristic triangle of light under the eye on the shadow side (Rembrandt) or a clean split down the center (split lighting). The subject's eyes catch the light with intensity and life, creating depth and magnetic presence. A subtle fill light or reflector at very low power maintains detail in shadows while preserving the dramatic mood. Possibly a gentle rim light separates the subject from the background, adding another dimension.

BLACK & WHITE MASTERY: Rendered in exquisite monochromatic tones with the full dynamic range of fine black and white photography. Deep, rich blacks with density and weight. Bright, clean highlights with detail and texture. An entire spectrum of nuanced gray tones throughout - from near-black charcoal through medium grays to bright silver highlights. There's subtle fine film grain present throughout the image, adding tactile texture and a cinematic, timeless quality reminiscent of medium format film photography. The grain is refined and sophisticated, never distracting, adding to the overall aesthetic.

TECHNICAL PERFECTION: Every detail is captured with stunning clarity and sharpness. Individual strands of hair are defined with texture and life. Skin shows authentic texture - natural pores, character lines that tell a story, genuine human detail. The weave and texture of fabric in the clothing is visible and dimensional. Eyelashes are crisp and defined. The iris shows intricate detail and depth. This level of clarity and detail is achieved through premium optics - imagine an 85mm f/1.4 or medium format portrait lens with exceptional resolving power, shot at optimal aperture for sharpness (f/4-f/5.6) while maintaining beautiful background separation.

EXPRESSION & PRESENCE: The subject's expression is powerful, contemplative, and deeply authentic. This is typically a more serious, thoughtful expression rather than a smile - think composed, introspective, strong, or contemplative. However, if the subject's natural expression in the original photo includes warmth or subtle smile, honor that authenticity while elevating it to editorial quality - perhaps a subtle, knowing expression or gentle strength rather than broad smile. The key is matching their natural energy while creating gravitas and presence. Their gaze is direct, engaging, and magnetic - the kind of eye contact that connects with viewers and holds their attention. There's intelligence, depth of character, confidence, and story in their eyes. This is a portrait that reveals something meaningful about who they are.

AUTHENTICITY & CHARACTER: Preserve every aspect of the subject's unique identity and authentic humanity with complete fidelity and reverence. Their exact facial structure, distinctive features, bone structure, natural skin tone and texture, hair color and style with all its natural character, eye color with authentic depth, and their unmistakable likeness. This is absolutely them, uniquely and truthfully. Embrace and celebrate natural skin texture - real pores, character lines that show a life lived, freckles, beauty marks, authentic human characteristics. Do not artificially smooth, blur, or diminish their natural features. In editorial black and white photography, these details become beautiful elements that add story, authenticity, and humanity. Every characteristic that makes them uniquely themselves is honored and preserved.

MOOD & AESTHETIC: The overall feeling is powerful, timeless, artistic, cinematic, and deeply sophisticated. This is fine art portraiture meets high-end editorial photography. The aesthetic evokes the iconic work of legendary portrait photographers - Annie Leibovitz's intimacy and storytelling, Peter Lindbergh's dramatic naturalism, Irving Penn's graphic elegance, or Yousuf Karsh's powerful character studies. It's the kind of portrait that stops people in their tracks, that belongs on the wall of a gallery, in the pages of Vanity Fair or The New York Times Magazine, or as the powerful author photo on a bestselling book.

This is perfect for artists, authors, executives, thought leaders, musicians, creatives, or anyone who wants a portrait with weight, presence, and artistic merit. The final image is dramatic, memorable, timeless, and utterly sophisticated - a portrait that reveals character and commands respect.`
} as const;

export type HeadshotStyle = keyof typeof HEADSHOT_PROMPTS;
